language: java
cache:
  directories: 
    - $HOME/.m2

services:
  - docker

before_install:
  - docker build -t cphb/assignment10-app -f webapp.Dockerfile .
  - docker build -t cphb/assignment10-selenium -f selenium.Dockerfile .

install: true 

script:
  - echo $TRAVIS_BUILD_DIR
  # unit 
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/app -w /app cphb/assignment10-app mvn -Dtest=cphb.AccountTest,cphb.CreditCardTest test
  # integration
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/app -w /app cphb/assignment10-app mvn -Dtest=cphb.AccountContrllerTest test

  # selenium
  - docker network create cphb-network
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/app -w /app -v $HOME/.m2:/root/.m2 --network cphb-network -d --name assignment10-app cphb/assignment10-app 
  - docker run --rm -v ${TRAVIS_BUILD_DIR}:/app -w /app -v $HOME/.m2:/root/.m2 --network cphb-network --name assignment10-selenium --env "APP_URL=http://app.test:8080" --link "assignment10-app:app.test" --name assignment10-selenium cphb/assignment10-selenium

deploy:
  provider: heroku
  api_key:
    secure: 3cJKGmAMPkJ5A/ZsgqUAeuIf2TqKhtPIb6dELt4siGeIuIUcxCUxlbet1guwKyKQR6PpmzUe82aF81ELliApl45HLCS+xw1/nAgOcj34D3m1Tp8Zl70epdP0OJQ3NQNezRZDL3nDH8j5llbLgPcKTLpoepW5ygebPp/KOV+yBS5JAOrubS5aHk4J7jboBggoO7jUazzFD1a9khQEEoMyDwbXCjKleiQGUMgXvGilLLXhB8BsQ7CLAwXMt/aLD+SVzzI7kuLJQxZ2M3mOczL2juQPBR1+m3cOxCJE2seURhkRRoPunzTArfoHHrN8TVKxhn6ttx04FHa4dl6NA0nGtJ1j1i5zkNvUQtAy0Yj/0L18SQRbxcdHg2m9RqNBeVVPmw/+V+shzb5vVB42+PfgkKRG9zxaYQL/EG91AyW2TSnruwIFy6UDyD0DQa37wdOdI87hwUBlFE1ptgW3k+SYhOYpramWrkgPoru2caQ5TPqhJtbyKjFhIAQW3hnFzdyIkoGd6u5vM0EIwTOv4gMKGbXPXvpAbtZwmv52aL0AhwSIhRrPt11LeoB470A0fAfRZzrnT4LE2HRSkISpCDLtXlBCyH00eB0SEqDjIm/4qzEDKR4pLZShpBnuPqZ2a5laqxX2xINgrl3YGFMcodZZqdnYqCRBcIycjc/cxoIEa/E=
  app: cphb-assignment10
  skip_cleanup: true